version: "3.8"

services:
    api-gym-pass:
        image: bitnami/postgresql:latest
        ports:
            - "5433:5432"
        environment:
            - POSTGRESQL_USERNAME=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DATABASE=gympass
